/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_smis_utubeopencv_OpencvNativeClass.h>
#include <src/main/include/HandRegion.h>

JNIEXPORT jint JNICALL Java_com_smis_utubeopencv_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong addrRgba, jlong addrGray) {

    Mat& mRgb = *(Mat*)addrRgba;
    Mat& mGray = *(Mat*)addrGray;

    int conv;
    jint retVal;
    conv = toGray(mRgb, mGray);

    HandRegion mHandRegionObj;

    mRgb = mHandRegionObj.GetHandRegion(mRgb, false);

    retVal = (jint) conv;

    return retVal;
  }

  int toGray(Mat img, Mat& gray){
    cvtColor(img, gray, CV_RGBA2GRAY);
    if(gray.rows == img.rows && gray.cols == img.cols )
    return 1;
    else
    return 0;
  }